AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.4.1

Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - '*.gemspec'

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/LineLength:
  Max: 82

Style/RegexpLiteral:
  EnforcedStyle: percent_r
