AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.5.0

Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - '*.gemspec'

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*.rb'

Style/ExpandPathArguments:
  Exclude:
    - '*.gemspec'

Metrics/LineLength:
  Max: 82

Style/RegexpLiteral:
  EnforcedStyle: percent_r

Style/FormatStringToken:
  Exclude:
    - 'lib/donation_system/utils.rb'

Metrics/AbcSize:
  Exclude:
    - 'lib/donation_system/input_data_validator.rb'
